export const DEFAULT_STUDIO_UI_TEXT = {
  "bulk_add_work": {
    "page_heading": "Bulk add work",
    "import_heading": "Import",
    "mode_label": "mode",
    "mode_option_works": "works",
    "mode_option_work_details": "work details",
    "workbook_label": "workbook",
    "summary_heading": "Preview summary",
    "details_heading": "Preview details",
    "loading": "loading bulk add work…",
    "empty_state": "",
    "preview_button": "Preview",
    "apply_button": "Import",
    "context_hint": "Bulk import is one-way from {workbook} into canonical JSON. Use works mode for new works and work details mode for new detail rows.",
    "summary_mode": "mode",
    "summary_workbook": "workbook",
    "summary_candidate_rows": "candidate rows",
    "summary_importable": "importable",
    "summary_duplicates": "duplicates",
    "summary_blocked": "blocked",
    "preview_empty": "Run preview to inspect workbook rows before import.",
    "section_importable": "importable",
    "section_duplicates": "duplicates already in source",
    "section_blocked": "blocked rows",
    "section_none": "none",
    "preview_status_running": "Running workbook import preview…",
    "preview_status_success": "Preview ready: {importable} importable, {duplicates} duplicates, {blocked} blocked.",
    "preview_blocked_warning": "Blocked rows must be fixed in {workbook} before apply.",
    "preview_status_failed": "Workbook import preview failed.",
    "apply_requires_preview": "Run preview for the current mode before apply.",
    "apply_status_running": "Applying workbook import…",
    "apply_status_success": "Workbook import completed.",
    "apply_result_success": "Imported {imported} record(s); {duplicates} duplicate record(s) already existed.",
    "apply_clear_workbook": "Clear the imported rows from {workbook} after you confirm the result.",
    "apply_status_failed": "Workbook import failed."
  },
  "catalogue_field_registry_review": {
    "page_heading": "catalogue field registry",
    "context_hint": "Read-only view of the active field-to-artifact registry used by catalogue build planning.",
    "loading": "loading catalogue field registry...",
    "empty_state": "",
    "search_placeholder": "field name",
    "output_label": "registry extract",
    "status_loaded": "Registry loaded.",
    "meta_all": "Showing full registry.",
    "meta_exact": "Showing {count} exact rule match(es) for field `{field}`.",
    "meta_partial": "Showing {count} partial rule match(es) for field search `{field}`."
  },
  "catalogue_series_editor": {
    "load_failed_error": "Failed to load catalogue source data for the series editor.",
    "search_placeholder": "find series by title",
    "search_empty": "Enter a series title or id.",
    "search_no_match": "No matching series records.",
    "missing_series_param": "Search for a series by title.",
    "unknown_series_error": "Unknown series id: {series_id}.",
    "open_button": "Open",
    "new_button": "New",
    "new_series_id_placeholder": "new series id",
    "new_series_id_label": "New series id",
    "save_button": "Save",
    "create_button": "Create",
    "publish_button": "Publish",
    "unpublish_button": "Unpublish",
    "delete_button": "Delete",
    "context_loaded": "Editing source metadata for series {series_id}.",
    "new_context_loaded": "Creating a draft series source record.",
    "dirty_warning": "Unsaved source changes.",
    "save_status_loaded": "Loaded series {series_id}.",
    "save_status_no_changes": "No changes to save.",
    "save_status_validation_error": "Fix validation errors before saving.",
    "save_status_saving": "Saving source record…",
    "save_status_saving_and_updating": "Saving source record and updating site…",
    "save_status_conflict": "Source record changed since this page loaded. Reload the series before saving again.",
    "save_status_failed": "Source save failed.",
    "save_result_success": "Source saved at {saved_at}. Public catalogue update still pending.",
    "save_result_success_applied": "Saved source changes and updated the public catalogue at {saved_at}.",
    "save_result_success_partial": "Source changes were saved at {saved_at}, but the public update failed.",
    "save_result_unchanged": "Source already matches the current form values.",
    "build_preview_template": "Site update preview: work {work_ids}; series {series_ids}; catalogue search {search_rebuild}.",
    "build_preview_search_yes": "yes",
    "build_preview_search_no": "no",
    "build_preview_failed": "Build preview unavailable.",
    "build_status_running": "Updating site…",
    "build_status_success": "Site update completed.",
    "build_status_failed": "Site update failed.",
    "build_result_success": "Public catalogue updated at {completed_at}. Studio Activity updated.",
    "publication_status_invalid": "Publication is available only for draft or published series.",
    "publication_save_first": "Save source changes before publishing.",
    "publication_status_validation_error": "Fix validation errors before changing publication state.",
    "publication_preview_publish_running": "Preparing publish preview…",
    "publication_preview_unpublish_running": "Preparing unpublish preview…",
    "publication_status_blocked": "Publication change is blocked.",
    "unpublish_confirm_default": "Unpublish this series?",
    "unpublish_confirm_dirty_note": "Unsaved form changes will be discarded.",
    "publication_unpublish_confirm_title": "Confirm unpublish",
    "publication_unpublish_confirm_button": "Unpublish",
    "publication_status_cancelled": "Publication change cancelled.",
    "publication_publish_running": "Publishing series…",
    "publication_unpublish_running": "Unpublishing series…",
    "publication_status_public_failed": "Publication state changed, but the public update failed.",
    "publication_result_public_failed": "Source status changed, but public artifacts did not finish updating.",
    "publication_status_published": "Series published.",
    "publication_result_published": "Series and attached draft works are published, and public catalogue output has been updated.",
    "publication_status_unpublished": "Series unpublished.",
    "publication_result_unpublished": "Series is draft again and public catalogue output has been cleaned up.",
    "publication_status_conflict": "Source record changed since this page loaded. Reload before changing publication state.",
    "publication_status_failed": "Publication change failed.",
    "create_status_validation_error": "Fix validation errors before creating the draft series.",
    "create_status_saving": "Creating draft series...",
    "create_status_success": "Created draft series {series_id}.",
    "create_status_failed": "Draft series create failed.",
    "create_result_success": "Created draft series {series_id}. Opening edit mode...",
    "delete_status_running": "Preparing delete preview...",
    "delete_status_blocked": "Delete is blocked.",
    "delete_status_cancelled": "Delete cancelled.",
    "delete_status_conflict": "Source record changed since this page loaded. Reload before deleting again.",
    "delete_status_failed": "Source delete failed.",
    "delete_status_r2_cleanup_warning": "Work deleted, but R2 media cleanup needs attention.",
    "delete_result_r2_cleanup_warning": "Remove the remaining R2 primary media manually for: {targets}.",
    "delete_confirm_title": "Confirm delete",
    "delete_confirm_default": "Delete this source record?",
    "delete_confirm_button": "Delete",
    "confirm_cancel_button": "Cancel",
    "modal_close_button": "Close",
    "field_invalid_status": "Use blank, draft, or published.",
    "field_required_series_id": "Enter a series id.",
    "field_duplicate_series_id": "Series id already exists.",
    "field_required_title": "Enter a title.",
    "field_required_series_type": "Choose a series type.",
    "field_invalid_series_type": "Choose a listed series type.",
    "field_required_year": "Enter a year.",
    "field_invalid_year": "Use a whole year.",
    "field_required_year_display": "Enter a year display.",
    "field_required_primary_work_publish": "Published series must have a primary work that belongs to this series.",
    "field_invalid_primary_work": "Primary work must be a current member of this series.",
    "members_heading": "Member works",
    "members_search_placeholder": "find member work by id",
    "members_search_no_match": "No matching member work ids.",
    "members_empty": "No works currently belong to this series.",
    "members_more_count": "showing {visible} of {total}",
    "members_add_placeholder": "add work by id",
    "members_add_button": "Add",
    "members_add_missing": "Enter a work id to add.",
    "members_add_unknown": "Unknown work id: {work_id}.",
    "members_add_exists": "Work {work_id} is already in this series.",
    "members_action_edit": "Edit",
    "members_action_new": "New",
    "members_action_new_unavailable": "Open a saved series before adding member works.",
    "members_action_primary": "Make primary",
    "members_action_remove": "Remove",
    "members_primary_badge": "primary",
    "members_position": "position {position}",
    "members_remove_blocked_primary": "work {work_id} is the primary work for this series, please set a different primary work before removing from the series",
    "members_remove_blocked_primary_only": "work {work_id} is the primary work for this series, and it is only associated with this series.",
    "members_remove_blocked_only_series": "work {work_id} is only associated with this series, so use the works editor to unpublish or delete it completely.",
    "members_remove_blocked_title": "Cannot remove work",
    "members_remove_confirm_title": "Remove work from series?",
    "members_remove_confirm_message": "Remove work {work_id} from this series?",
    "members_remove_confirm_note": "This does not delete the work source record. Save to persist the membership change.",
    "members_remove_confirm_button": "Remove",
    "members_remove_staged": "Removed work {work_id} from this series. Save to persist the membership change.",
    "summary_public_link": "Open public series page",
    "summary_member_count": "Member works",
    "summary_rebuild_needed": "public update failed in this session",
    "summary_rebuild_current": "source and public catalogue are aligned in this session",
    "new_meta": "draft source record",
    "new_summary_series_id_label": "series id",
    "new_summary_status_label": "status",
    "new_summary_status": "draft source record; not published",
    "new_summary_next_label": "next step",
    "new_summary_next": "Create the draft, then add member works, set primary_work_id, and publish when ready.",
    "new_runtime_state": "Public site update is unavailable until the draft series exists."
  },
  "catalogue_status": {
    "load_failed_error": "Failed to load catalogue drafts.",
    "empty_state": "No draft {family}.",
    "meta_summary": "{count} draft {family}",
    "meta_summary_one": "1 draft {family}"
  },
  "catalogue_work_editor": {
    "load_failed_error": "Failed to load catalogue source data for the work editor.",
    "load_requested_work_failed": "Failed to load the requested work.",
    "search_placeholder": "find work id(s): 00001, 00003-00005",
    "search_empty": "Enter a work id.",
    "search_no_match": "No matching work ids.",
    "missing_work_param": "Search for a work by work id.",
    "unknown_work_error": "Unknown work id: {work_id}.",
    "open_button": "Open",
    "new_button": "New",
    "save_button": "Save",
    "create_button": "Create",
    "delete_button": "Delete",
    "publish_button": "Publish",
    "unpublish_button": "Unpublish",
    "new_status_loaded": "Creating a draft work source record.",
    "new_work_id_label": "New work id",
    "new_work_id_placeholder": "new work id",
    "new_meta": "Creating a draft work.",
    "new_runtime_state": "Public site update is unavailable until the draft exists.",
    "new_summary_status_label": "status",
    "new_summary_status": "draft source record; not published",
    "new_summary_next_label": "next step",
    "new_summary_next": "Create the draft, then continue editing or publish from edit mode.",
    "dirty_warning": "Unsaved source changes.",
    "series_picker_label": "Find series by title",
    "series_picker_placeholder": "find series by title",
    "series_picker_empty": "No series selected.",
    "field_required_work_id": "Enter a work id.",
    "field_duplicate_work_id": "Work id already exists.",
    "field_required_title": "Enter title.",
    "field_required_year": "Enter year.",
    "field_required_year_display": "Enter year display.",
    "field_required_series_ids": "Select at least one series.",
    "create_status_validation_error": "Fix validation errors before creating the draft work.",
    "create_status_saving": "Creating draft work...",
    "create_status_success": "Created draft work {work_id}.",
    "create_status_failed": "Draft work create failed.",
    "create_result_success": "Created draft work {work_id}. Opening edit mode...",
    "save_status_loaded": "",
    "bulk_status_loaded": "Loaded {count} work records.",
    "save_status_no_changes": "No changes to save.",
    "save_status_validation_error": "Fix validation errors before saving.",
    "save_status_saving": "Saving source record…",
    "save_status_saving_and_updating": "Saving source record and updating parent work output…",
    "save_status_conflict": "Source record changed since this page loaded. Reload the work before saving again.",
    "save_status_failed": "Source save failed.",
    "save_result_success": "Source saved at {saved_at}.",
    "save_result_success_unpublished": "Source saved at {saved_at}.",
    "save_result_success_applied": "Saved source changes and updated the public catalogue at {saved_at}.",
    "save_result_success_partial": "Source changes were saved at {saved_at}, but the public update failed.",
    "save_result_unchanged": "Source already matches the current form values.",
    "bulk_save_result_success": "Saved {count} work records at {saved_at}.",
    "bulk_save_result_success_applied": "Saved {count} work records and updated public catalogue output for published records at {saved_at}.",
    "bulk_save_result_success_partial": "Saved {count} work records at {saved_at}, but the public update failed.",
    "build_preview_template": "Public update preview: work {work_ids}; series {series_ids}; catalogue search {search_rebuild}.",
    "build_preview_search_yes": "yes",
    "build_preview_search_no": "no",
    "build_preview_failed": "Public update preview unavailable.",
    "build_preview_unpublished": "Public update unavailable while the work is not published.",
    "build_status_running": "Updating site…",
    "build_status_success": "Site update completed.",
    "build_status_failed": "Site update failed.",
    "build_result_success": "Public catalogue updated at {completed_at}. Studio Activity updated.",
    "bulk_build_preview": "Public update preview: {count} published work scope(s) will be updated.",
    "publication_status_invalid": "Publication is available only for draft or published works.",
    "publication_save_first": "Save source changes before publishing.",
    "publication_status_validation_error": "Fix validation errors before changing publication state.",
    "publication_preview_publish_running": "Preparing publish preview…",
    "publication_preview_unpublish_running": "Preparing unpublish preview…",
    "publication_status_blocked": "Publication change is blocked.",
    "unpublish_confirm_default": "Unpublish this work?",
    "unpublish_confirm_dirty_note": "Unsaved form changes will be discarded.",
    "publication_unpublish_confirm_title": "Confirm unpublish",
    "publication_unpublish_confirm_button": "Unpublish",
    "publication_status_cancelled": "Publication change cancelled.",
    "publication_publish_running": "Publishing work…",
    "publication_unpublish_running": "Unpublishing work…",
    "publication_status_public_failed": "Publication state changed, but the public update failed.",
    "publication_result_public_failed": "Source status changed, but public artifacts did not finish updating.",
    "publication_status_published": "Work published.",
    "publication_result_published": "Work is published and public catalogue output has been updated.",
    "publication_status_unpublished": "Work unpublished.",
    "publication_result_unpublished": "Work is draft again and public catalogue output has been cleaned up.",
    "publication_status_conflict": "Source record changed since this page loaded. Reload before changing publication state.",
    "publication_status_failed": "Publication change failed.",
    "media_refresh_button": "Refresh media",
    "media_refresh_status_running": "Refreshing media…",
    "media_refresh_status_success": "Media refresh completed.",
    "media_refresh_status_failed": "Media refresh failed.",
    "media_refresh_status_blocked": "Media refresh blocked.",
    "media_publish_preview_running": "Checking R2 media…",
    "media_publish_status_running": "Publishing media to R2…",
    "media_publish_status_success": "Media published.",
    "media_publish_status_success_version": "Media published. Confirmed URL version: v={media_version}.",
    "media_publish_status_failed": "Media publishing failed.",
    "media_publish_status_blocked": "Media publishing is blocked.",
    "media_publish_status_cancelled": "Media publishing cancelled.",
    "media_publish_status_conflict": "The confirmed media version changed. Reload before publishing media.",
    "media_publish_confirm_title": "Publish R2 media?",
    "media_publish_overwrite_confirm_title": "Replace R2 media?",
    "media_publish_confirm_button": "Publish media",
    "media_publish_overwrite_confirm_button": "Replace media",
    "media_publish_result_complete": "R2 media publishing completed.",
    "delete_status_running": "Preparing delete preview...",
    "delete_status_deleting": "Deleting source record...",
    "delete_status_blocked": "Delete is blocked.",
    "delete_status_cancelled": "Delete cancelled.",
    "delete_status_conflict": "Source record changed since this page loaded. Reload before deleting again.",
    "delete_status_failed": "Source delete failed.",
    "delete_confirm_title": "Confirm delete",
    "delete_confirm_default": "Delete this source record?",
    "delete_confirm_button": "Delete",
    "confirm_cancel_button": "Cancel",
    "field_invalid_date": "Use YYYY-MM-DD or leave blank.",
    "field_invalid_year": "Use a whole year or leave blank.",
    "field_invalid_number": "Use a number or leave blank.",
    "field_invalid_status": "Use blank, draft, or published.",
    "field_invalid_series_id": "Use comma-separated numeric series ids.",
    "field_unknown_series_id": "Unknown series id: {series_id}.",
    "summary_series_label": "series",
    "details_heading": "work details",
    "details_new_link": "new work detail →",
    "details_new_unavailable_draft": "Publish this work before adding work details.",
    "details_search_placeholder": "find detail by id",
    "details_search_no_match": "No matching detail ids for this work.",
    "details_empty": "No work details for this work.",
    "details_more_count": "showing {visible} of {total}",
    "details_section_blank": "root",
    "details_search_results": "matching details",
    "detail_section_edit_button": "Edit",
    "detail_section_delete_button": "Delete",
    "detail_section_new_button": "New",
    "detail_section_picker_title": "New detail section",
    "detail_section_picker_confirm_button": "Create",
    "detail_section_picker_subfolder_required": "Select a subfolder.",
    "detail_section_create_status_running": "Creating detail section...",
    "detail_section_create_status_created": "Created detail section with {count} detail file(s).",
    "detail_section_create_status_exists": "Detail section already exists.",
    "detail_section_create_status_failed": "Detail section create failed.",
    "detail_section_create_status_r2_warning": "Detail section created, but R2 media publishing needs attention.",
    "detail_section_create_result_r2_warning": "Publish the remaining R2 primary media manually for: {targets}.",
    "detail_section_edit_modal_title": "Edit detail section",
    "detail_section_title_label": "section title",
    "detail_section_order_label": "order",
    "detail_section_detail_sort_label": "detail sort",
    "detail_section_detail_sort_id": "id",
    "detail_section_detail_sort_title": "title",
    "detail_section_edit_title_required": "Enter a section title.",
    "detail_section_edit_order_invalid": "Enter a section order from 1 to {count}.",
    "detail_section_edit_sort_invalid": "Choose a detail sort.",
    "detail_section_edit_status_saving": "Saving detail section...",
    "detail_section_edit_status_saved": "Saved detail section {section_id}.",
    "detail_section_edit_status_unchanged": "Detail section already matches the current values.",
    "detail_section_edit_status_failed": "Detail section save failed.",
    "detail_section_delete_status_running": "Preparing detail section delete preview...",
    "detail_section_delete_status_deleting": "Deleting detail section...",
    "detail_section_delete_status_blocked": "Detail section delete is blocked.",
    "detail_section_delete_status_cancelled": "Detail section delete cancelled.",
    "detail_section_delete_status_deleted": "Deleted detail section {section_id}.",
    "detail_section_delete_status_failed": "Detail section delete failed.",
    "detail_section_delete_status_r2_warning": "Detail section deleted, but R2 media cleanup needs attention.",
    "detail_section_delete_result_r2_warning": "Remove the remaining R2 primary media manually for: {targets}.",
    "detail_section_delete_confirm_title": "Confirm detail section delete",
    "detail_section_delete_confirm_button": "Delete",
    "files_heading": "downloads",
    "files_empty": "No downloads for this work.",
    "files_add_button": "Add file",
    "files_edit_button": "Edit",
    "files_delete_button": "Delete",
    "files_add_modal_title": "Add download",
    "files_edit_modal_title": "Edit download",
    "files_delete_modal_title": "Delete download",
    "files_delete_modal_body": "Delete download {label}?",
    "files_filename_label": "filename",
    "files_label_label": "label",
    "files_invalid_filename": "Each download needs a filename.",
    "files_invalid_label": "Each download needs a label.",
    "links_heading": "links",
    "links_empty": "No links for this work.",
    "links_add_button": "Add link",
    "links_edit_button": "Edit",
    "links_delete_button": "Delete",
    "links_add_modal_title": "Add link",
    "links_edit_modal_title": "Edit link",
    "links_delete_modal_title": "Delete link",
    "links_delete_modal_body": "Delete link {label}?",
    "links_url_label": "URL",
    "links_label_label": "label",
    "links_invalid_url": "Each link needs a URL.",
    "links_invalid_label": "Each link needs a label.",
    "entry_modal_save_button": "Save",
    "entry_modal_cancel_button": "Cancel",
    "entry_modal_delete_button": "Delete",
    "summary_rebuild_needed": "public update failed in this session"
  },
  "project_state": {
    "page_heading": "project state",
    "run_heading": "report",
    "output_label": "output",
    "source_label": "source",
    "include_subfolders_label": "include sub-folders",
    "summary_heading": "summary",
    "loading": "loading project state...",
    "empty_state": "",
    "run_button": "Run",
    "open_button": "Open file",
    "context_hint": "Scan source project folders and primary images against works.json, then write the Markdown report. Include sub-folders only when you want nested project folders in the review.",
    "summary_include_subfolders": "include sub-folders",
    "summary_source_folders": "source folders",
    "summary_catalogue_folders": "catalogue folders",
    "summary_unrepresented_folders": "folders not in works.json",
    "summary_source_images": "source images",
    "summary_catalogue_images": "primary images in works.json",
    "summary_unrepresented_images": "extra images in represented folders",
    "run_status_running": "Running project-state report...",
    "run_status_success": "Project-state report updated.",
    "run_result_success": "Report written to {path}.",
    "run_status_failed": "Project-state report failed.",
    "open_failed": "Could not open the Markdown report."
  },
  "studio_works": {
    "copy_series_button": "copy series"
  }
};
