export const DEFAULT_TAG_UI_TEXT = {
  series_tag_editor: {
    missing_series_id_error: "Tag editor error: missing series id.",
    load_failed_error: "Failed to load tag data. Check /studio/api/tags/tag-registry, /studio/api/tags/tag-aliases, /studio/api/tags/tag-assignments, /assets/data/series_index.json, and /assets/data/works_index.json.",
    work_input_placeholder: "add works in this series",
    tag_input_placeholder: "tag or alias",
    add_button: "Add",
    save_button: "Save",
    context_hint_default: "No work selected: edit series tags directly. Select a work to switch to work-only overrides.",
    context_hint_selected: "Monochrome pills are inherited from the series. Colored pills are saved as work-only overrides.",
    popup_heading_works: "works",
    popup_heading_tags: "tags",
    popup_heading_aliases: "aliases",
    empty_state: "",
    work_input_required: "Enter a work id from this series.",
    work_input_required_multiple: "Enter at least one work id from this series.",
    work_unknown_error: "Unknown work id for this series: \"{input}\".",
    work_multiple_matches: "Multiple works match \"{input}\". Choose one from the popup.",
    work_not_in_series_error: "Work {work_id} is not in this series.",
    work_selected_success: "Selected work {work_id}.",
    work_summary_added: "Added {count} work{plural}.",
    work_summary_not_in_series: "Not in this series: {list}.",
    work_summary_invalid: "Invalid work id: {list}.",
    tag_input_required: "Enter a tag or alias.",
    tag_multiple_matches: "Multiple matches for \"{input}\": {candidate_ids}{suffix}. Choose one from autocomplete.",
    tag_unknown_error: "Unknown tag: \"{input}\".",
    tag_inherited_warning: "Inherited from series already: {tag_id}.",
    tag_already_added_warning_series: "Already added to series: {tag_id}.",
    tag_already_added_warning: "Already added for {work_id}: {tag_id}.",
    series_tag_added_success: "Added {tag_id} to series tags.",
    tag_added_success: "Added {tag_id} to {work_id}.",
    series_tag_removed: "Series tag removed.",
    work_tag_removed: "Work tag removed.",
    weight_updated: "Updated {tag_id} w_manual to {weight}.",
    remove_selected_work_aria_label: "Remove selected work {work_id}",
    series_tag_title: "Series tag {tag_id}",
    inherited_tag_title: "Inherited from series: {tag_id}",
    work_override_title: "Work override {tag_id}",
    weight_button_title: "w_manual {weight}",
    weight_button_aria_label: "w_manual {weight}",
    remove_series_tag_aria_label: "Remove {tag_id}",
    remove_work_tag_aria_label: "Remove {tag_id}",
    save_warning_unresolved: "Resolve unknown tags before saving.",
    save_warning_pending_diff: "Save to persist the current tag assignment diff.",
    save_status_no_changes: "No changes to save.",
    save_status_local_failed: "Local save failed.",
    save_result_local_failed: "Changes remain unsaved in this editor.",
    save_status_success_series: "Saved series tags",
    save_status_success_base: "Saved {saved_count} work row{saved_plural}",
    save_status_success_removed_suffix: "; removed {removed_count} row{removed_plural}",
    save_status_success_at_suffix: " at {saved_at}."
  },
  series_tags: {
    load_failed_error: "Failed to load series tag data.",
    empty_state: "none",
    table_heading_series: "series",
    table_heading_status: "status",
    table_heading_tags: "tags",
    filter_all_tags: "All tags"
  },
  tag_aliases: {
    load_failed_error: "Failed to load aliases from /studio/api/tags/tag-aliases.",
    new_alias_button: "New alias",
    search_label: "Search aliases",
    search_placeholder: "search",
    all_tags_filter: "All tags [{count}]",
    table_heading_alias: "alias",
    group_tags_heading: "tags",
    empty_state: "none",
    edit_modal_title: "Edit Alias",
    new_modal_title: "New Alias",
    edit_alias_label: "alias",
    edit_description_label: "description",
    edit_search_placeholder: "search tags",
    edit_save_button: "Save",
    edit_create_button: "Create",
    edit_cancel_button: "Cancel",
    alias_edit_title: "Edit alias {alias}",
    alias_edit_aria_label: "Edit alias {alias}",
    alias_promote_title: "Promote alias to canonical tag",
    alias_promote_aria_label: "Promote alias {alias}",
    alias_delete_title: "Delete alias",
    alias_delete_aria_label: "Delete alias {alias}",
    tag_demote_title: "Demote canonical tag to alias",
    tag_demote_aria_label: "Demote {tag_id}",
    remove_target_tag_aria_label: "Remove {tag_id}",
    popup_more_title: "More matches available",
    alias_not_found: "Alias not found: {alias_key}",
    edit_no_changes: "No changes.",
    alias_required: "Alias is required.",
    alias_invalid: "Alias must be lowercase letters, numbers, or hyphens.",
    alias_exists_warning: "Alias already exists.",
    select_one_tag_warning: "Select at least one tag.",
    max_tags_warning: "Select up to {max_tags} tags.",
    unknown_tag_selected: "Unknown tag selected: {tag_id}",
    one_tag_per_group_warning: "Only one tag per group is allowed ({group}).",
    server_create_failed: "Server create failed; switched to patch mode. {message}",
    server_save_failed: "Server save failed; switched to patch mode. {message}",
    server_delete_failed: "Server delete failed; switched to patch mode. {message}",
    delete_confirm_template: "Delete alias \"{alias_key}\"?",
    delete_success_summary: "deleted alias {alias_key}",
    promotion_modal_title: "Promote Alias",
    promotion_modal_prompt: "Choose the canonical tag group for this alias.",
    promotion_button: "Promote",
    promotion_cancel_button: "Cancel",
    promotion_group_required: "Choose a group.",
    promotion_group_invalid: "Promotion group must be one of: subject, domain, form, theme.",
    promotion_alias_meta: "Alias: {alias_key}",
    promotion_preview_failed: "Promotion preview failed.",
    promoted_success: "Promoted.",
    promotion_failed: "Promotion failed.",
    demotion_modal_title: "Demote Tag to Alias",
    demotion_modal_meta: "tag: {tag_id} -> alias \"{alias_key}\"",
    demotion_search_placeholder: "search tags",
    demotion_confirm_button: "Demote",
    demotion_cancel_button: "Cancel",
    demotion_confirm_template: "Demote \"{tag_id}\" to alias \"{alias_key}\"?\n\nTargets: {targets}\n\nImpact:\n{preview_summary}",
    invalid_target_tags: "Invalid target tags.",
    alias_value_invalid_tag_id: "Invalid alias tag_id value.",
    alias_tags_array_required: "Alias tags must be an array.",
    alias_tags_required: "Alias tags must include at least one tag_id.",
    alias_tags_max: "Alias tags may include at most {max_tags} tags.",
    alias_tag_array_invalid_value: "Invalid alias tag_id array value.",
    alias_tags_one_per_group: "Alias tags may include only one tag per group: {group}",
    target_tag_invalid: "Invalid tag_id: {value}",
    target_tag_required: "At least one canonical target tag_id is required.",
    target_tags_max: "At most {max_tags} target tags are allowed.",
    target_tags_one_per_group: "Only one target tag per group is allowed ({group}).",
    demotion_target_self: "Target list must not include the demoted tag.",
    demotion_preview_failed: "Demotion preview failed.",
    demoted_success: "Demoted.",
    demotion_failed: "Demotion failed.",
    patch_modal_title: "Aliases Patch Preview",
    patch_modal_label: "Manual patch snippet",
    patch_modal_copy_button: "Copy",
    patch_modal_close_button: "Close",
    patch_copy_success: "Patch snippet copied to clipboard.",
    patch_copy_failed: "Copy failed. Select and copy the snippet manually.",
    patch_promote_message: "Patch mode: section snippets prepared for promoting \"{alias_key}\".",
    patch_delete_message: "Patch mode: remove this alias key from studio/data/canonical/tags/tag-aliases.json aliases object.",
    patch_create_message: "Patch mode: alias fragment prepared for new alias \"{alias_key}\". Paste inside aliases object.",
    patch_edit_rename_note: " Also remove old alias key \"{alias_key}\" from studio/data/canonical/tags/tag-aliases.json.",
    patch_edit_message: "Patch mode: alias fragment prepared for \"{alias_key}\". Paste inside aliases object.{rename_note}",
    patch_demote_message: "Patch mode: section snippets prepared for demoting \"{tag_id}\"."
  },
  tag_groups: {
    load_failed_error: "Failed to load group descriptions from /studio/api/tags/tag-groups.",
    empty_state: "No group descriptions available.",
    description_long_fallback: "No long description available."
  },
  tag_registry: {
    load_failed_error: "Failed to load tag data from /studio/api/tags/tag-registry and /studio/api/tags/tag-aliases.",
    new_tag_button: "New tag",
    search_label: "Search tags",
    search_placeholder: "search",
    all_tags_filter: "All tags [{count}]",
    empty_state: "none",
    table_heading_tag: "tag",
    table_heading_description: "description",
    table_heading_updated: "updated",
    edit_modal_title: "Edit Tag",
    edit_description_label: "description",
    edit_save_button: "Save",
    edit_close_button: "Close",
    new_modal_title: "New Tag",
    new_slug_label: "tag",
    new_create_button: "Create",
    new_cancel_button: "Cancel",
    demote_modal_title: "Demote Tag to Alias",
    demote_search_label: "find target tags",
    demote_search_placeholder: "search tags",
    demote_confirm_button: "Demote",
    demote_close_button: "Close",
    delete_modal_title: "Delete Tag",
    delete_impact_intro: "Deleting this tag also removes matching tag assignments and removes this tag from aliases. Aliases left with no targets are deleted.",
    delete_confirm_button: "Delete",
    delete_close_button: "Cancel",
    tag_edit_aria_label: "Edit {tag_id}",
    tag_demote_title: "Demote canonical tag to alias",
    tag_demote_aria_label: "Demote {tag_id}",
    tag_delete_title: "Delete canonical tag",
    tag_delete_aria_label: "Delete {tag_id}",
    remove_target_tag_aria_label: "Remove {tag_id}",
    local_edit_required: "Local server is required for edit.",
    selected_tag_missing: "Selected tag is no longer available.",
    edit_no_changes: "No changes to save.",
    edit_saved: "Saved.",
    edit_save_failed: "Save failed.",
    select_group_warning: "Select a tag group.",
    tag_slug_required: "Tag is required.",
    tag_slug_invalid: "Tag must be lowercase letters, numbers, or hyphens.",
    tag_exists_warning: "Tag already exists.",
    server_create_failed: "Server create failed; switched to two-source patch mode. {message}",
    create_failed: "Create failed.",
    local_delete_required: "Local server is required for delete.",
    delete_impact_unavailable_local: "Delete impact: unavailable (local server required).",
    delete_impact_unavailable: "Delete impact: unavailable.",
    delete_impact_template: "Delete impact: {summary}",
    delete_impact_error_template: "Delete impact: {message}",
    delete_impact_series: "series affected",
    delete_impact_aliases_updated: "aliases updated",
    delete_impact_aliases_deleted: "aliases deleted",
    delete_failed: "Delete failed.",
    alias_exists_demote_error: "Alias already exists: {alias_key}. Demotion overwrite is not permitted.",
    demote_select_target_warning: "Select at least one target tag.",
    demote_max_tags_warning: "Select up to {max_tags} tags.",
    demote_target_includes_self: "Target list must not include the demoted tag.",
    demote_unknown_tag_warning: "Unknown tag selected: {tag_id}",
    demote_one_per_group_warning: "Only one target tag per group is allowed ({group}).",
    popup_more_title: "More matches available",
    demote_invalid_targets: "Invalid target tags.",
    demote_confirm_template: "Demote \"{tag_id}\" to alias \"{alias_key}\"?\n\nTargets: {targets}\n\nImpact:\n{preview_summary}",
    demote_preview_failed: "Demotion preview failed.",
    demoted_success: "Demoted.",
    demotion_failed: "Demotion failed.",
    patch_modal_title: "Registry Patch Preview",
    patch_modal_label: "Manual patch snippet",
    patch_modal_copy_button: "Copy",
    patch_modal_close_button: "Close",
    patch_copy_success: "Patch snippet copied to clipboard.",
    patch_copy_failed: "Copy failed. Select and copy the snippet manually.",
    patch_demote_message: "Patch mode: section snippets prepared for demoting \"{tag_id}\".",
    patch_create_message: "Patch mode: linked Registry row and Analysis tag document prepared; nothing has been written."
  }
};
