export const DEFAULT_ADMIN_UI_TEXT = {
  admin_activity: {
    load_failed_error: "Failed to load Admin activity.",
    empty_state: "No Admin activity yet.",
    meta_summary: "{count} recent activity rows",
    meta_summary_one: "1 recent activity row",
    column_time: "date-time",
    column_status: "status",
    column_page: "page",
    column_user_action: "user action",
    column_script_purpose: "script purpose",
    status_completed: "completed",
    status_warning: "warning",
    status_failed: "failed",
    status_other: "status unknown",
    record_group_works: "works",
    record_group_series: "series",
    record_group_details: "details",
    record_group_moments: "moments",
    record_group_docs: "docs",
    record_group_files: "files",
    record_group_search: "search",
    record_group_tags: "tags",
    record_group_aliases: "aliases",
    modal_title: "Activity details",
    modal_close_button: "Close",
    modal_empty_detail: "No detail items recorded."
  },
  admin_audits: {
    intro: "Run local Admin maintenance audits.",
    run_button: "Run audit",
    running_button: "Running...",
    idle_status: "Select an audit to run.",
    service_unavailable: "Audit API unavailable. Start bin/local-admin to run audits.",
    status_running: "Running audit...",
    status_passed: "Audit passed.",
    status_failed: "Audit failed.",
    status_request_failed: "Audit request failed.",
    output_label: "output"
  },
  admin_checks: {
    idle_status: "Choose a report and target filters.",
    service_unavailable: "Checks API unavailable. Start bin/local-admin to run checks.",
    report_label: "report",
    scope_label: "scope",
    family_label: "family",
    area_label: "area",
    route_label: "route",
    all_option: "< all >",
    run_button: "Run",
    running_button: "Running...",
    status_running: "Running checks...",
    status_passed: "Checks run completed.",
    status_failed: "Checks run failed.",
    status_request_failed: "Checks request failed.",
    delete_button: "Delete",
    delete_confirm: "Delete checks snapshot {run_id}?",
    delete_status_running: "Deleting snapshot...",
    delete_status_deleted: "Checks snapshot deleted.",
    delete_status_failed: "Checks snapshot delete failed.",
    runs_label: "run folders",
    no_runs: "No checks runs found.",
    markdown_empty: "No report selected.",
    artifact_path_label: "artifact"
  }
};
